title: Lerntagebuch CAW
author: Nathalie
email: 
description: > # this means to ignore newlines until "baseurl:"
  Vorlage für ein Lerntagebuch im Kurs Bibliotheks- und Archivinformatik FS2020

# social links
github_username:  felixlohmeier # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
